buildscript {
    repositories {
        jcenter()
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'org.spongepowered.mixin'

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

version = "1.0.0"
group = "com.yuki920.betterchatmod"
archivesBaseName = "betterchatmod"

minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "run"
    mappings = "stable_22"
    
    makeObfSourceJar = false
}

repositories {
    maven { url = "https://repo.spongepowered.org/maven" }
}

configurations {
    shade
    compile.extendsFrom shade
}

dependencies {
    shade('org.spongepowered:mixin:0.8.5') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
    }
}

mixin {
    add sourceSets.main, "mixins.betterchatmod.refmap.json"
}

jar {
    configurations.shade.each { dep ->
        from(project.zipTree(dep)) {
            exclude 'META-INF', 'META-INF/**'
        }
    }
    
    manifest.attributes(
        "TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
        "TweakOrder": 0,
        "FMLCorePluginContainsFMLMod": "true",
        "ForceLoadAsMod": "true",
        "MixinConfigs": "mixins.betterchatmod.json"
    )
}
